language: cpp
os: linux
dist: focal

script:
  - make -j 8
  - make buildtests && make test

env:
  global:
    - OMP_NUM_THREADS=4
    - TIMEOUT=1000

addons:
  apt:
    update: true
    packages:
      - util-linux
      - clang-9
      - g++-9
      - cmake
      - libomp-dev
      - libgl1-mesa-dev
      - xorg-dev
      - libglu1-mesa-dev
      - libxrandr-dev
      - libxcb-randr0-dev
      - libxinerama-dev
      - libglm-dev
      - libassimp-dev
      - libeigen3-dev
      - libglew-dev
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-bionic-9
  homebrew:
    update: true
    packages:
      - libomp
      - glm
      - eigen
      - assimp
      - fmt

before_install:
  - export CHECKOUT_PATH=`pwd`;
  - if [ -n "$GCC_VERSION" ]; then export CXX="g++-${GCC_VERSION}" CC="gcc-${GCC_VERSION}"; fi
  - if [ -n "$CLANG_VERSION" ]; then export CXX="clang++-${CLANG_VERSION}" CC="clang-${CLANG_VERSION}"; fi
  - $CXX --version
  - cmake --version
  - |
    if [[ "$TRAVIS_OS_NAME" = "linux" ]]; then
      sudo add-apt-repository --yes ppa:beineri/opt-qt-5.15.0-focal
      sudo apt --yes update
      sudo apt --yes install qt515base qt515svg qt515multimedia
      source /opt/qt515/bin/qt515-env.sh
    fi;

jobs:
  include:
    # mac clang Release
    - env:
        - PREFIX_PATH="/usr/local/opt/qt/lib/cmake"
        - BUILD_TYPE=Release
        - BUILD_DOC=Off
      os: osx
      compiler: clang

    # linx clang Release
    - env:
        - QT5_PATH="~/Qt/5.15.0/gcc_64"
        - BUILD_TYPE=Release
        - CLANG_VERSION=9
        - BUILD_DOC=Off
        - MATRIX_EVAL=""
      os: linux
      dist: focal
      compiler: clang

    # linx gcc Release
    - env:
        - QT5_PATH="~/Qt/5.15.0/gcc_64"
        - BUILD_TYPE=Release
        - GCC_VERSION=9
        - BUILD_DOC=Off
      os: linux
      dist: focal
      compiler: gcc

install:
  - cd $CHECKOUT_PATH
  - mkdir -p build
  - cd build
  - cmake .. -DCMAKE_C_COMPILER=$CC -DCMAKE_CXX_COMPILER=$CXX -DCMAKE_BUILD_TYPE=${BUILD_TYPE} -DCMAKE_PREFIX_PATH=${PREFIX_PATH} -DQt5_DIR=${QT5_PATH}