language: cpp

script:
  - make -j 8
  - make buildtests && make test

env:
  global:
    - OMP_NUM_THREADS=4
    - TIMEOUT=1000

addons:
  apt:
    update: true
    packages:
      - util-linux
      - clang-5.0
      - g++-7
      - cmake
      - libgl1-mesa-dev
      - libxrandr-dev
      - libxcb-randr0-dev
      - libglm-dev
  homebrew:
    update: true
    packages:
      - glm

before_install:
  - export CHECKOUT_PATH=`pwd`;
  - eval "${MATRIX_EVAL}"
  - if [ -n "$GCC_VERSION" ]; then export CXX="g++-${GCC_VERSION}" CC="gcc-${GCC_VERSION}"; fi
  - if [ -n "$CLANG_VERSION" ]; then export CXX="clang++-${CLANG_VERSION}" CC="clang-${CLANG_VERSION}"; fi
  - $CXX --version
  - cmake --version
# install eigen
  - git clone --recurse-submodules https://gitlab.com/libeigen/eigen.git
  - cd eigen && mkdir -p build && cd build
  - cmake .. && sudo make install
  - cd ../..
# install spdlog
  - git clone --recurse-submodules https://github.com/gabime/spdlog.git
  - cd spdlog && mkdir -p build && cd build
  - cmake .. && sudo make install
  - cd ../..
# install glfw3
  - git clone --recurse-submodules https://github.com/glfw/glfw.git
  - cd glfw && mkdir -p build && cd build
  - cmake .. && sudo make install
  - cd ../..

jobs:
  include:
    # mac clang Release
    - env:
        - BUILD_TYPE=Release
        - BUILD_DOC=Off
        - MATRIX_EVAL=""
      os: osx
      compiler: clang

    # linx clang Release
    - env:
        - BUILD_TYPE=Release
        - CLANG_VERSION=5.0
        - BUILD_DOC=Off
        - MATRIX_EVAL=""
      os: linux
      addons: &clang50
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-bionic-5.0

    # linx gcc Release
    - env:
        - BUILD_TYPE=Release
        - GCC_VERSION=7
        - BUILD_DOC=Off
        - MATRIX_EVAL=""
      os: linux
      addons: &gcc7
        apt:
          sources:
            - ubuntu-toolchain-r-test

install:
  - cd $CHECKOUT_PATH
  - mkdir -p build
  - cd build
  - cmake .. -DCMAKE_C_COMPILER=$CC -DCMAKE_CXX_COMPILER=$CXX -DCMAKE_BUILD_TYPE=${BUILD_TYPE} -DCMAKE_PREFIX_PATH=/usr/include/