configuration: Release

image: Visual Studio 2019

environment:
  REPO_ROOT: C:\projects\Engine

clone_folder: C:\projects\Engine

install:
  - set Qt5_DIR=C:\Qt\5.15.0\msvc2019_64
  - appveyor DownloadFile http://repo.msys2.org/distrib/x86_64/msys2-x86_64-20150916.exe
  - msys2-x86_64-20150916.exe
  - C:\msys64\usr\bin\bash --login -c "pacman -Sy --noconfirm pacman"
  - C:\msys64\usr\bin\bash --login -c "pacman -Syu --noconfirm"
  - C:\msys64\usr\bin\bash --login -c "pacman -Su --noconfirm"
  - C:\msys64\usr\bin\bash --login -c "pacman -S --noconfirm mingw-w64-{x86_64,i686}-toolchain"
  - cd C:\Tools\vcpkg
  - git pull
  - .\bootstrap-vcpkg.bat
  - cd %REPO_ROOT%

before_build:
  - vcpkg install glm:x64-windows eigen3:x64-windows assimp:x64-windows spdlog:x64-windows
  - vcpkg integrate install
  - git submodule update --init --recursive
  - cmd: md build
  - cmd: cd build

build_script:
  - cmake -DCMAKE_TOOLCHAIN_FILE="C:/Tools/vcpkg/scripts/buildsystems/vcpkg.cmake" -G "Visual Studio 16 2019" -A x64 ..
  - cmake --build . --target buildtests
  - ctest -C %configuration%