configuration: Release

image: Visual Studio 2019

environment:
  REPO_ROOT: C:\projects\Engine

clone_folder: C:\projects\Engine

install:
  - set Qt5_DIR=C:\Qt\5.15.0\msvc2019_64
  - C:\msys64\usr\bin\bash --login -c "pacman -Sy --noconfirm pacman-mirrors"
  - C:\msys64\usr\bin\bash --login -c "pacman -S --noconfirm pacman"
  - C:\msys64\usr\bin\bash --login -c "pacman --sync --noconfirm VCS"
  - C:\msys64\usr\bin\bash --login -c "pacman --sync --noconfirm base-devel msys2-devel mingw-w64-{x86_64,i686}-toolchain"
  - C:\msys64\usr\bin\bash --login -c "pacman --sync --noconfirm mingw-w64-{x86_64,i686}-cmake"
  - C:\msys64\usr\bin\bash --login -c "pacman --sync --noconfirm mingw-w64-{x86_64,i686}-ninja"
  - C:\msys64\usr\bin\bash --login -c "pacman --sync --noconfirm mingw-w64-{x86_64,i686}-gtkmm"
  - C:\msys64\usr\bin\bash --login -c "pacman --sync --noconfirm mingw-w64-{x86_64,i686}-wxWidgets"
  - C:\msys64\usr\bin\bash --login -c "pacman --sync --noconfirm cmake"
  - C:\msys64\usr\bin\bash --login -c "pacman -Syyuu"
  - C:\msys64\usr\bin\bash --login -c "pacman -Su"
  - cd C:\Tools\vcpkg
  - git pull
  - .\bootstrap-vcpkg.bat
  - cd %REPO_ROOT%

before_build:
  - vcpkg install glm:x64-windows eigen3:x64-windows assimp:x64-windows spdlog:x64-windows
  - vcpkg integrate install
  - git submodule update --init --recursive
  - cmd: md build
  - cmd: cd build

build_script:
  - cmake -DCMAKE_TOOLCHAIN_FILE="C:/Tools/vcpkg/scripts/buildsystems/vcpkg.cmake" -G "Visual Studio 16 2019" -A x64 ..
  - cmake --build . --target buildtests
  - ctest -C %configuration%