configuration: Release

image: Visual Studio 2017

environment:
  REPO_ROOT: C:\projects\Engine

clone_folder: C:\projects\Engine

install:
  - set Qt5_DIR=C:\Qt\5.15.0\msvc2017_64
  - cd C:\Tools\vcpkg
  - git pull
  - .\bootstrap-vcpkg.bat

before_build:
  - vcpkg install glm:x64-windows eigen3:x64-windows assimp:x64-windows spdlog:x64-windows
  - vcpkg integrate install
  - cd %REPO_ROOT%
  - git submodule update --init --recursive
  - cmd: md build
  - cmd: cd build

build_script:
  - cmake -DCMAKE_TOOLCHAIN_FILE="C:/Tools/vcpkg/scripts/buildsystems/vcpkg.cmake" -G "Visual Studio 15 2017" -A x64 ..
  - cmake --build . --target buildtests
  - ctest -C %configuration%