configuration: Release

environment:
  REPO_ROOT: C:\projects\Engine

  matrix:
    - APPVEYOT_BUILD_WORKER_IMAGE: Visual Studio 2019
	  MSVC_SETUP_PATH: C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\vcvarsall.bat
	  MSVC_SETUP_ARGS: x64

clone_floder: C:\projects\Engine

install:
  - cd C:\Tools\vcpkg
  - git pull
  - .\bootstrap-vcpkg.bat
  - cd %REPO_ROOT%

before_build:
  - vcpkg install glm:x64-windows eigen3:x64-windows assimp:x64-windows spdlog:x64-windows glfw3:x64-windows
  - vcpkg integrate install
  - call "%MSVC_SETUP_PATH%" %MSVC_SETUP_ARGS%
  - cmd: md build
  - cmd: cd build

build_script:
  - cmake -DCMAKE_TOOLCHAIN_FILE="C:/Tools/vcpkg/scripts/buildsystems/vcpkg.cmake" -G "Visual Studio 16 2019" -A x64 ..
  - cmake --build . --target buildtests
  - ctest -C %configuration%